import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { Boxes, CheckCircle2, ClipboardPlus, Download, FileSpreadsheet, PackageCheck, RefreshCw, Send, Wrench } from "lucide-react";
import Modal from "../../components/Modal";
import { getApiMessage } from "../../features/access/api";
import { createReboxing, createRepalletRequest, downloadConditioningBilling, downloadConditioningService, executeRepallet, getConditioningOptions, getConditioningServices, sendConditioningToBilling } from "../../features/conditioning/api";
import type { ConditioningOptions, ConditioningService, ReboxingPayload, RepalletExecutionPayload, RepalletRequestPayload } from "../../features/conditioning/types";
import { useAuth } from "../../features/auth/auth-context";

type ModalKind = "request" | "execute" | "reboxing" | null;
const initialRequest: RepalletRequestPayload = { codigo: "", id_cliente: 0, id_stock: 0, descripcion: "", cantidad: "", cliente_provee_pallet_destino: false, tipo_pallet_destino: "Estándar de exportación", certificacion_destino: "", observaciones: "" };
const initialExecution: RepalletExecutionPayload = { cantidad: "", numero_paletas: 1, tarifa: "", codigo_pallet_destino: "", tipo_pallet_destino: "Estándar de exportación", certificacion_destino: "", descripcion: "", observaciones: "" };
const initialReboxing: ReboxingPayload = { codigo: "", id_stock: 0, descripcion: "", cantidad: "", cantidad_cajas_origen: 1, cantidad_cajas_destino: 1, tarifa: "", observaciones: "" };

function dateTime(value: string | null) { return value ? new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
function money(value: string | number) { return new Intl.NumberFormat("es-PE", { style: "currency", currency: "PEN" }).format(Number(value || 0)); }
function badge(value: string) { return <span className={`conditioning-badge ${value.toLowerCase()}`}>{value.replaceAll("_", " ")}</span>; }
function stockLabel(stock: ConditioningOptions["stocks"][number]) { return `${stock.producto?.sku ?? "Stock"} · ${stock.producto?.nombre ?? "Producto"} · ${stock.ubicacion?.codigo ?? "Sin ubicación"} · disp. ${stock.cantidad_disponible}`; }

export default function ConditioningPage() {
  const { profile } = useAuth();
  const permissions = useMemo(() => new Set(profile?.permisos ?? []), [profile?.permisos]);
  const canRequest = permissions.has("acondicionamiento.solicitar");
  const canExecute = permissions.has("acondicionamiento.ejecutar");
  const canBill = permissions.has("acondicionamiento.facturacion");
  const [services, setServices] = useState<ConditioningService[]>([]);
  const [options, setOptions] = useState<ConditioningOptions>({ clientes: [], stocks: [] });
  const [filters, setFilters] = useState({ q: "", tipo: "", estado: "", estado_facturacion: "" });
  const [modal, setModal] = useState<ModalKind>(null);
  const [selected, setSelected] = useState<ConditioningService | null>(null);
  const [requestForm, setRequestForm] = useState(initialRequest);
  const [executionForm, setExecutionForm] = useState(initialExecution);
  const [reboxingForm, setReboxingForm] = useState(initialReboxing);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const [rows, optionRows] = await Promise.all([getConditioningServices(filters), getConditioningOptions()]);
      setServices(rows); setOptions(optionRows);
    } catch (currentError) { setError(getApiMessage(currentError)); }
    finally { setLoading(false); }
  }, [filters]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  const metrics = useMemo(() => ({
    requested: services.filter((item) => item.estado === "SOLICITADO").length,
    completed: services.filter((item) => item.estado === "COMPLETADO").length,
    billing: services.filter((item) => item.estado === "COMPLETADO" && item.estado_facturacion !== "ENVIADO").length,
    total: services.filter((item) => item.estado === "COMPLETADO").reduce((sum, item) => sum + Number(item.importe_total), 0),
  }), [services]);
  const clientStocks = options.stocks.filter((stock) => !requestForm.id_cliente || stock.cliente?.id_cliente === requestForm.id_cliente);

  async function submit(operation: () => Promise<unknown>, success: string) {
    setBusy(true); setError(null); setNotice(null);
    try { await operation(); setNotice(success); setModal(null); setSelected(null); await load(); return true; }
    catch (currentError) { setError(getApiMessage(currentError)); return false; }
    finally { setBusy(false); }
  }
  function openExecution(item: ConditioningService) {
    setSelected(item);
    setExecutionForm({ ...initialExecution, cantidad: item.cantidad, descripcion: item.descripcion, tipo_pallet_destino: item.detalle?.tipo_pallet_destino || initialExecution.tipo_pallet_destino, certificacion_destino: item.detalle?.certificacion_destino || "" });
    setModal("execute");
  }
  async function submitRequest(event: FormEvent) { event.preventDefault(); if (await submit(() => createRepalletRequest(requestForm), "Solicitud de repaletizado registrada como facturable.")) setRequestForm(initialRequest); }
  async function submitExecution(event: FormEvent) { event.preventDefault(); if (selected) await submit(() => executeRepallet(selected.id_servicio, executionForm), "Repaletizado ejecutado y listo para facturación."); }
  async function submitReboxing(event: FormEvent) { event.preventDefault(); if (await submit(() => createReboxing(reboxingForm), "Reencajado registrado y listo para facturación.")) setReboxingForm(initialReboxing); }

  return <section className="management-page conditioning-page">
    <header className="page-heading"><div><span className="page-eyebrow">EP-09 · Acondicionamiento de mercadería</span><h1>Servicios de repaletizado y reencajado</h1><p>Registra solicitudes, evidencia la ejecución y entrega cargos trazables a facturación.</p></div><div className="page-actions">{canBill && <><button className="secondary-button" type="button" onClick={() => void downloadConditioningBilling("xlsx")}><FileSpreadsheet size={15}/>Excel facturación</button><button className="secondary-button" type="button" onClick={() => void downloadConditioningBilling("pdf")}><Download size={15}/>PDF</button></>}{canExecute && <button className="secondary-button" type="button" onClick={() => setModal("reboxing")}><Boxes size={15}/>Registrar reencajado</button>}{canRequest && <button className="action-button" type="button" onClick={() => setModal("request")}><ClipboardPlus size={15}/>Solicitar repaletizado</button>}</div></header>
    {error && <div className="inline-alert" role="alert"><span>{error}</span><button type="button" onClick={() => setError(null)}>Cerrar</button></div>}
    {notice && <div className="conditioning-notice"><CheckCircle2 size={17}/>{notice}</div>}
    <div className="conditioning-kpis"><article><span><Wrench size={19}/></span><div><small>Solicitudes pendientes</small><strong>{metrics.requested}</strong></div></article><article><span><PackageCheck size={19}/></span><div><small>Servicios completados</small><strong>{metrics.completed}</strong></div></article><article><span><Send size={19}/></span><div><small>Pendientes de envío</small><strong>{metrics.billing}</strong></div></article><article><span><FileSpreadsheet size={19}/></span><div><small>Importe completado</small><strong>{money(metrics.total)}</strong></div></article></div>
    <div className="conditioning-filters"><label>Buscar<input value={filters.q} onChange={(event) => setFilters({ ...filters, q: event.target.value })} placeholder="Código o descripción"/></label><label>Servicio<select value={filters.tipo} onChange={(event) => setFilters({ ...filters, tipo: event.target.value })}><option value="">Todos</option><option value="REPALETIZADO">Repaletizado</option><option value="REENCAJADO">Reencajado</option></select></label><label>Operación<select value={filters.estado} onChange={(event) => setFilters({ ...filters, estado: event.target.value })}><option value="">Todos</option><option value="SOLICITADO">Solicitado</option><option value="COMPLETADO">Completado</option></select></label><label>Facturación<select value={filters.estado_facturacion} onChange={(event) => setFilters({ ...filters, estado_facturacion: event.target.value })}><option value="">Todos</option><option value="PENDIENTE">Pendiente</option><option value="GENERADO">Reporte generado</option><option value="ENVIADO">Enviado</option></select></label><button className="secondary-button" type="button" onClick={() => void load()}><RefreshCw size={15}/>Actualizar</button></div>
    {loading ? <div className="content-loading"><span className="loading-spinner"/>Cargando servicios…</div> : <div className="data-card conditioning-table-card"><table className="data-table conditioning-table"><thead><tr><th>Servicio</th><th>Cliente / Mercadería</th><th>Ejecución</th><th>Cargo facturable</th><th>Estados</th><th>Acciones</th></tr></thead><tbody>{services.map((item) => <tr key={item.id_servicio}><td><div className="table-stack"><strong>{item.codigo}</strong><small>{item.tipo.replace("REPALETIZADO", "Repaletizado").replace("REENCAJADO", "Reencajado")}</small><small>{dateTime(item.fecha_solicitud)}</small></div></td><td><div className="table-stack"><strong>{item.cliente?.razon_social ?? "—"}</strong><small>{item.stock?.producto?.sku ?? "—"} · {item.stock?.producto?.nombre ?? "Sin producto"}</small><small>{item.descripcion}</small></div></td><td><div className="table-stack"><strong>{item.cantidad} unidades</strong><small>{item.detalle?.numero_paletas ? `${item.detalle.numero_paletas} paleta(s)` : item.detalle?.cantidad_cajas_destino ? `${item.detalle.cantidad_cajas_origen} → ${item.detalle.cantidad_cajas_destino} cajas` : "Pendiente"}</small><small>{dateTime(item.fecha_ejecucion)}</small></div></td><td><div className="table-stack"><strong>{money(item.importe_total)}</strong><small>{item.unidades_facturables} {item.unidad_facturacion.toLowerCase()} × {money(item.tarifa)}</small></div></td><td><div className="conditioning-statuses">{badge(item.estado)}{badge(item.estado_facturacion)}</div></td><td><div className="table-actions">{canExecute && item.tipo === "REPALETIZADO" && item.estado === "SOLICITADO" && <button type="button" onClick={() => openExecution(item)}>Ejecutar</button>}{canBill && item.estado === "COMPLETADO" && <><button type="button" onClick={() => void downloadConditioningService(item.id_servicio, item.codigo, "pdf")}><Download size={13}/>Reporte</button>{item.estado_facturacion !== "ENVIADO" && <button type="button" onClick={() => void submit(() => sendConditioningToBilling(item.id_servicio), `${item.codigo} enviado a facturación.`)}><Send size={13}/>Enviar</button>}</>}</div></td></tr>)}</tbody></table>{services.length === 0 && <div className="empty-state"><PackageCheck size={28}/><strong>Sin servicios para mostrar</strong><span>Registra una solicitud o cambia los filtros.</span></div>}</div>}

    {modal === "request" && <Modal title="Solicitar repaletizado" description="La solicitud queda marcada como servicio facturable." onClose={() => setModal(null)}><form className="management-form" onSubmit={submitRequest}><div className="form-grid"><label>Código<input required value={requestForm.codigo} onChange={(event) => setRequestForm({ ...requestForm, codigo: event.target.value })} placeholder="REP-0001"/></label><label>Cliente<select required value={requestForm.id_cliente} onChange={(event) => setRequestForm({ ...requestForm, id_cliente: Number(event.target.value), id_stock: 0 })}><option value={0}>Seleccionar cliente</option>{options.clientes.map((item) => <option key={item.id_cliente} value={item.id_cliente}>{item.razon_social} · {item.ruc}</option>)}</select></label></div><label>Mercadería / stock<select required value={requestForm.id_stock} onChange={(event) => setRequestForm({ ...requestForm, id_stock: Number(event.target.value) })}><option value={0}>Seleccionar stock disponible</option>{clientStocks.map((item) => <option key={item.id_stock} value={item.id_stock}>{stockLabel(item)}</option>)}</select></label><div className="form-grid"><label>Cantidad<input required min="0.0001" step="0.0001" type="number" value={requestForm.cantidad} onChange={(event) => setRequestForm({ ...requestForm, cantidad: event.target.value })}/></label><label>Tipo de paleta destino<input required value={requestForm.tipo_pallet_destino} onChange={(event) => setRequestForm({ ...requestForm, tipo_pallet_destino: event.target.value })}/></label></div><label>Descripción<textarea required rows={2} value={requestForm.descripcion} onChange={(event) => setRequestForm({ ...requestForm, descripcion: event.target.value })}/></label><div className="form-grid"><label>Certificación / fumigación<input value={requestForm.certificacion_destino} onChange={(event) => setRequestForm({ ...requestForm, certificacion_destino: event.target.value })} placeholder="NIMF-15, certificado…"/></label><label className="switch-row"><span>El cliente provee la paleta<small>Registra el origen de la paleta destino.</small></span><input type="checkbox" checked={requestForm.cliente_provee_pallet_destino} onChange={(event) => setRequestForm({ ...requestForm, cliente_provee_pallet_destino: event.target.checked })}/></label></div><label>Observaciones<textarea rows={2} value={requestForm.observaciones} onChange={(event) => setRequestForm({ ...requestForm, observaciones: event.target.value })}/></label><div className="modal-actions"><button className="secondary-button" type="button" onClick={() => setModal(null)}>Cancelar</button><button className="action-button" type="submit" disabled={busy}>{busy ? "Guardando…" : "Registrar solicitud"}</button></div></form></Modal>}
    {modal === "execute" && selected && <Modal title={`Ejecutar ${selected.codigo}`} description="Registra la evidencia operativa y la tarifa del repaletizado." onClose={() => setModal(null)}><form className="management-form" onSubmit={submitExecution}><div className="form-grid"><label>Cantidad ejecutada<input required min="0.0001" step="0.0001" type="number" value={executionForm.cantidad} onChange={(event) => setExecutionForm({ ...executionForm, cantidad: event.target.value })}/></label><label>Número de paletas<input required min="1" type="number" value={executionForm.numero_paletas} onChange={(event) => setExecutionForm({ ...executionForm, numero_paletas: Number(event.target.value) })}/></label></div><div className="form-grid"><label>Código paleta destino<input required value={executionForm.codigo_pallet_destino} onChange={(event) => setExecutionForm({ ...executionForm, codigo_pallet_destino: event.target.value })}/></label><label>Tarifa por paleta (S/)<input required min="0.01" step="0.01" type="number" value={executionForm.tarifa} onChange={(event) => setExecutionForm({ ...executionForm, tarifa: event.target.value })}/></label></div><div className="form-grid"><label>Tipo de paleta<input required value={executionForm.tipo_pallet_destino} onChange={(event) => setExecutionForm({ ...executionForm, tipo_pallet_destino: event.target.value })}/></label><label>Certificación<input value={executionForm.certificacion_destino} onChange={(event) => setExecutionForm({ ...executionForm, certificacion_destino: event.target.value })}/></label></div><label>Descripción de la ejecución<textarea required rows={2} value={executionForm.descripcion} onChange={(event) => setExecutionForm({ ...executionForm, descripcion: event.target.value })}/></label><label>Observaciones<textarea rows={2} value={executionForm.observaciones} onChange={(event) => setExecutionForm({ ...executionForm, observaciones: event.target.value })}/></label><div className="modal-actions"><button className="secondary-button" type="button" onClick={() => setModal(null)}>Cancelar</button><button className="action-button" type="submit" disabled={busy}>{busy ? "Registrando…" : "Confirmar ejecución"}</button></div></form></Modal>}
    {modal === "reboxing" && <Modal title="Registrar reencajado" description="El registro queda completado y disponible para facturación." onClose={() => setModal(null)}><form className="management-form" onSubmit={submitReboxing}><div className="form-grid"><label>Código<input required value={reboxingForm.codigo} onChange={(event) => setReboxingForm({ ...reboxingForm, codigo: event.target.value })} placeholder="REN-0001"/></label><label>Mercadería / stock<select required value={reboxingForm.id_stock} onChange={(event) => setReboxingForm({ ...reboxingForm, id_stock: Number(event.target.value) })}><option value={0}>Seleccionar stock disponible</option>{options.stocks.map((item) => <option key={item.id_stock} value={item.id_stock}>{stockLabel(item)}</option>)}</select></label></div><div className="form-grid"><label>Cantidad<input required min="0.0001" step="0.0001" type="number" value={reboxingForm.cantidad} onChange={(event) => setReboxingForm({ ...reboxingForm, cantidad: event.target.value })}/></label><label>Tarifa por unidad (S/)<input required min="0.01" step="0.01" type="number" value={reboxingForm.tarifa} onChange={(event) => setReboxingForm({ ...reboxingForm, tarifa: event.target.value })}/></label></div><div className="form-grid"><label>Cajas de origen<input required min="1" type="number" value={reboxingForm.cantidad_cajas_origen} onChange={(event) => setReboxingForm({ ...reboxingForm, cantidad_cajas_origen: Number(event.target.value) })}/></label><label>Cajas de destino<input required min="1" type="number" value={reboxingForm.cantidad_cajas_destino} onChange={(event) => setReboxingForm({ ...reboxingForm, cantidad_cajas_destino: Number(event.target.value) })}/></label></div><label>Descripción<textarea required rows={2} value={reboxingForm.descripcion} onChange={(event) => setReboxingForm({ ...reboxingForm, descripcion: event.target.value })}/></label><label>Observaciones<textarea rows={2} value={reboxingForm.observaciones} onChange={(event) => setReboxingForm({ ...reboxingForm, observaciones: event.target.value })}/></label><div className="modal-actions"><button className="secondary-button" type="button" onClick={() => setModal(null)}>Cancelar</button><button className="action-button" type="submit" disabled={busy}>{busy ? "Registrando…" : "Registrar reencajado"}</button></div></form></Modal>}
  </section>;
}
